package CounterPOA;


/**
* CounterPOA/CountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from count.idl
* Wednesday, October 3, 2012 12:40:21 PM PDT
*/

public interface CountOperations 
{
  int sum ();
  void sum (int newSum);
  int increment ();
} // interface CountOperations
