package CounterPOA;

/**
* CounterPOA/CountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from count.idl
* Wednesday, October 3, 2012 12:40:21 PM PDT
*/

public final class CountHolder implements org.omg.CORBA.portable.Streamable
{
  public CounterPOA.Count value = null;

  public CountHolder ()
  {
  }

  public CountHolder (CounterPOA.Count initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CounterPOA.CountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CounterPOA.CountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CounterPOA.CountHelper.type ();
  }

}
