package CounterPOA;


/**
* CounterPOA/Count.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from count.idl
* Wednesday, October 3, 2012 12:40:21 PM PDT
*/

public interface Count extends CountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Count
